jobs:
- template: build.yml  # Template reference
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: build.yml  # Template reference
  parameters:
    name: Ubuntu1604
    pool:
      vmImage: 'ubuntu-16.04'

- template: build.yml  # Template reference
  parameters:
    name: Ubuntu1804
    pool:
      vmImage: 'ubuntu-18.04'
