parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - script: ~/.cargo/bin/cargo build
  - script: ls target/debug
  - task: DownloadBuildArtifacts@0
    inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: ${{ parameters.name }}
        downloadPath: '$(System.ArtifactsDirectory)'


