parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - script: ~/.cargo/bin/cargo build
  - task: PublishPipelineArtifact@0
    inputs:
        artifactName: ${{ parameters.name }}
        targetPath: 'target/debug/rst'


