parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - script: source ~/.bash_profile
  - script: cargo build

