parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - script: ~/.cargo/bin/cargo build
  - script: ls
  - script: ls target
  - script: ls target/debug
  - task: CopyFiles@0
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'target/debug/rst'
  - task: PublishPipelineArtifact@0
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: rst


